truncate table F_ROLEPOWER;
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '00000121');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000002');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000003');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000004');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000005');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000007');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000009');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000011');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000014');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000015');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000016');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000025');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000035');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000039');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000040');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000044');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000045');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000046');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000047');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000048');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000049');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000050');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000051');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000052');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000053');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000054');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000055');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000056');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000057');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000058');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000059');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000060');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000061');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000062');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000068');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000069');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000070');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000071');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000072');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000073');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000074');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000075');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000076');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000088');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000091');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000092');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000093');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000094');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000095');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000096');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000105');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000110');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000115');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000116');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000117');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000118');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000119');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000120');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000121');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000122');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000127');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000128');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '000129');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000146');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000147');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000148');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000149');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000154');

insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000155');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000156');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000157');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000158');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000159');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000160');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000161');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000162');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000163');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000164');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000165');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000166');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000167');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000168');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000169');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000170');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000171');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000172');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000173');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000174');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000175');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000176');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000177');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000178');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000179');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000180');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000181');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000182');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000183');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000184');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000185');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000186');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000187');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000188');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000189');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000190');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000191');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000192');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000193');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000194');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000195');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000196');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000197');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000198');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000199');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000200');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000201');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000202');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000203');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000204');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000205');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000206');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000207');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000208');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000209');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000210');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000211');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000212');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000213');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000214');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000215');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000216');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000217');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000218');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000219');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000220');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000221');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000222');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000223');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000224');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000225');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000226');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000227');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000228');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000229');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000230');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000231');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000232');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000233');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000234');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000235');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000236');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000237');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000238');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000239');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000240');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000241');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000256');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000257');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000258');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000259');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000260');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000261');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000262');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000263');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000264');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000265');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000268');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000269');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000270');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000271');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-SYSADMIN', '10000273');

insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-anonymous', '000068');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-anonymous', '000069');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-anonymous', '000070');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-anonymous', '000071');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-anonymous', '000072');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-anonymous', '000092');
insert into F_ROLEPOWER (ROLECODE, OPTCODE)
values ('G-anonymous', '000095');

commit;

