server:
  port: 10089
  servlet:
    contextPath: /dde
spring:
  application:
    name: DDE-KAFKA-CONSUMER
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.137.63:31426/locodedata?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: stat
    password: stat
    dbcp2:
      max-wait-millis: 10000
      max-idle: 15
      initial-size: 10
      validation-query: SELECT 1 from dual
      connection-properties: characterEncoding=utf8

consumer:
  #指定了线程池中的线程数量，它的数量决定了添加的任务是开辟新的线程去执行，还是放到workQueue任务队列中去
  corePoolSize: 5
  #指定了线程池中的最大线程数量，这个参数会根据你使用的workQueue任务队列的类型，决定线程池会开辟的最大线程数量；
  maximumPoolSize: 30
  #当线程池中空闲线程数量超过corePoolSize时，多余的线程会在多长时间内被销毁 单位：毫秒
  keepAliveTime: 5000
  #初始化等待队列大小
  queueSize: 10








